### ISSUE TITLE
Bot Login - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by nikebooom** [joe27g/EnhancedDiscord-Plugins#13]
makes my discord not work at all https://gyazo.com/409fa9117337c01c5118a9c02e5d4187

**Comment by ThatLifeofGames** [comment]
Literally a dupe of #12, the only other issue here...

**Comment by joe27g** [comment]
What he said, + I'm going to close all Discord Source issues from now on. Like this one, they are usually pointless and/or duplicates.
