### ISSUE TITLE
Experiments - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by VXkiller85** [joe27g/EnhancedDiscord-Plugins#15]
https://github.com/joe27g/EnhancedDiscord/blob/master/plugins/experiments.js gets a 404 error

**Comment by ThatLifeofGames** [comment]
That's not an issue with ED that's an issue with the site you're using. Don't open it as an issue here.
https://github.com/joe27g/EnhancedDiscord-Plugins/blob/master/experiments.js is the correct link.

**Comment by VXkiller85** [comment]
> That's not an issue with ED that's an issue with the site you're using. Don't open it as an issue here.
> https://github.com/joe27g/EnhancedDiscord-Plugins/blob/master/experiments.js is the correct link.

Oh now I feel stupid. Thanks for the help
