### ISSUE TITLE
Login screen bug.

### ISSUE THREAD

**Issue by iINexusIi** [joe27g/EnhancedDiscord-Plugins#20]
Every time i put in the bot key and close out of discord completely it takes me to the login screen.
(yes i follow all the steps you have put into play, ive tried to do it multiple times)

**Comment by iINexusIi** [comment]
Nevermind, its fixed, although. Im stuck in a loop when I log into a bit account, says something about an invalid session ID

**Comment by joe27g** [comment]
Bot login has been removed in 71f9a18, as it appears Discord is actually doing something to stop it from working. (Also closed #12 for this reason)
