### ISSUE TITLE
i drop the script in plugin folder but it's not in the list and i got EnhancedDiscord 

### ISSUE THREAD

**Issue by x0rld** [joe27g/EnhancedDiscord-Plugins#3]
![image](https://user-images.githubusercontent.com/45242856/51448282-b8076a80-1d25-11e9-9fb9-d8e8209e6dfa.png)
![pluginbug](https://user-images.githubusercontent.com/45242856/51448289-cfdeee80-1d25-11e9-919d-2e3095624418.jpg)

**Comment by rauenzi** [comment]
You have BetterDiscord/BandagedBD installed. Plugins in this repo are for EnhancedDiscord...

**Comment by thomas-samaan** [comment]
but i installed EnhancedDiscord too

**Comment by rauenzi** [comment]
They are separate Discord mods they shouldn't be installed together; They don't really work together.

**Comment by rauenzi** [comment]
Also even if the plugin worked it wouldn't show in the list you screenshotted, that's completely separate.

**Comment by thomas-samaan** [comment]
oh ok i didn't know they don't work together
