### ISSUE TITLE
I dropped the script into the plugin folder but it isn't showing up in the list and i got BetterDiscord

### ISSUE THREAD

**Issue by Mohithchowdary** [joe27g/EnhancedDiscord-Plugins#4]
It isn't showing up to enable hidden channels.

**Comment by IndyV** [comment]
Pretty sure BD doesn't support any ED plugins.
If you mean ED with BD plugin support, it helps to specify which plugin isn't working.

**Comment by IndyV** [comment]
Looking further into this...

EnhancedDiscord has the [hidden channels plugin](https://github.com/joe27g/EnhancedDiscord/blob/master/plugins/hidden_channels.js) (Authored by [Joe](https://github.com/joe27g)) by default and is not even part of this repository. 

I assume you got this [show hidden channel plugin from BetterDiscordAddons](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ShowHiddenChannels) (Authored by [mwittrien](https://github.com/mwittrien)). Which is for BetterDiscord only.
Again if you have BetterDiscord installed then this repository is not much use to you.
