### ISSUE TITLE
Experiments - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by S-B99** [joe27g/EnhancedDiscord-Plugins#7]
https://github.com/joe27g/EnhancedDiscord/blob/master/plugins/experiments.js is down

**Comment by hamsterofficial** [comment]
It is moved to plugin repo... https://github.com/joe27g/EnhancedDiscord-Plugins/blob/master/experiments.js

**Comment by joe27g** [comment]
> It is moved to plugin repo... https://github.com/joe27g/EnhancedDiscord-Plugins/blob/master/experiments.js

Yep. Idk how you managed to post this issue on the repo which it was moved to without noticing, but ok

**Comment by S-B99** [comment]
That's a new one. discordsource.com didn't update the download link but updated the report an issue link.

**Comment by rauenzi** [comment]
Well that's an unofficial site so you can't and shouldn't expect too much

**Comment by jakuski** [comment]
Agreed, instead of publishing an issue here, you should post an issue on the site's respective repo. It is not our duty to inform and update third-party sites about events such as these.
