### ISSUE TITLE
Bot Login Doesn't work at all. 

### ISSUE THREAD

**Issue by S-B99** [joe27g/EnhancedDiscord-Plugins#8]
Followed step by step.

Add `token` under application > local storage, including quotes as in `"tokenhere"`

Install plugin

Relaunch Discord.

Doesn't work, sometimes it asks me to sign back into with my regular account.

**Comment by hamsterofficial** [comment]
bot login is broken.

**Comment by Cr3atable** [comment]
@hamsterofficial that's what this issue is about, you don't have to repeat it
even then, Joe just recently released a patch to fix it, so it should work.

**Comment by joe27g** [comment]
I just tested it and it worked fine. Make sure ED and your Discord client are up-to date. If you're using Canary or PTB, then use the stable version, as I have no intention to maintain these for other versions. Otherwise, just follow the directions closely and it should work.

**Comment by S-B99** [comment]
Stable, both BBD and Discord are latest. I literally followed the instructions to the letter nobody could mess them up.

**Comment by IndyV** [comment]
BBD? This repo is called EnhancedDiscord-Plugins so I'm not sure how you would be able to run it

**Comment by rauenzi** [comment]
The README even explicitly says that these are for EnhancedDiscord. Sounds like you didn't follow too closely.
