### ISSUE TITLE
Bot Login

### ISSUE THREAD

**Issue by explasion** [joe27g/EnhancedDiscord-Plugins#9]
Causes discord to freeze, screenshot below:
http://tinyurl.com/yyfcgyyb

**Comment by explasion** [comment]
Also the reload or "crash" issue isn't fixed but it's just a part of how discord works, since it thinks you have no valid authorization, it checks again, and every time https://discordapp.com/api/v6/users/@me 401's due to the header for "authorization" being invalid it fails.

Furthermore, the header it sends for that (at least only using EDSettings and Bot Login on Discord PTB) is this (screenshot): http://tinyurl.com/y3jkq9hr

**Comment by explasion** [comment]
Also apparently this plugin conflicts with the bdapi for bandaged/betterdiscord plugins, because it will always, in my experience, fail to log you in if you have the setting to enable those set to true.

**Comment by Earu** [comment]
It would be great to see this fixed!

**Comment by hickleydonate** [comment]
will it be fixed soon?
